//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.1432.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="RelevanceBinding", Namespace="http://schemas.bigfix.com/Relevance")]
public partial class RelevanceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback GetRelevanceResultOperationCompleted;
    
    /// <remarks/>
    public RelevanceService() {
        this.Url = "http://razorbill:52312/webreports";
    }
    
    /// <remarks/>
    public event GetRelevanceResultCompletedEventHandler GetRelevanceResultCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.bigfix.com/Relevance/GetRelevanceResult", RequestNamespace="http://schemas.bigfix.com/Relevance", ResponseNamespace="http://schemas.bigfix.com/Relevance", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("a")]
    public string[] GetRelevanceResult(string relevanceExpr, string username, string password) {
        object[] results = this.Invoke("GetRelevanceResult", new object[] {
                    relevanceExpr,
                    username,
                    password});
        return ((string[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetRelevanceResult(string relevanceExpr, string username, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetRelevanceResult", new object[] {
                    relevanceExpr,
                    username,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public string[] EndGetRelevanceResult(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string[])(results[0]));
    }
    
    /// <remarks/>
    public void GetRelevanceResultAsync(string relevanceExpr, string username, string password) {
        this.GetRelevanceResultAsync(relevanceExpr, username, password, null);
    }
    
    /// <remarks/>
    public void GetRelevanceResultAsync(string relevanceExpr, string username, string password, object userState) {
        if ((this.GetRelevanceResultOperationCompleted == null)) {
            this.GetRelevanceResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRelevanceResultOperationCompleted);
        }
        this.InvokeAsync("GetRelevanceResult", new object[] {
                    relevanceExpr,
                    username,
                    password}, this.GetRelevanceResultOperationCompleted, userState);
    }
    
    private void OnGetRelevanceResultOperationCompleted(object arg) {
        if ((this.GetRelevanceResultCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetRelevanceResultCompleted(this, new GetRelevanceResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void GetRelevanceResultCompletedEventHandler(object sender, GetRelevanceResultCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetRelevanceResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetRelevanceResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string[])(this.results[0]));
        }
    }
}

