//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigFixExcelConnector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BigFixExcelConnector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;us-ascii&quot;?&gt;
        ///&lt;BES&gt;
        ///
        ///  &lt;FixletType&gt;
        ///    &lt;fixlets text=&quot;Common Properties&quot; imageindex=&quot;5&quot; tag=&quot;Object&quot;&gt;
        ///      &lt;fixlets text=&quot;Applicable Computer Count&quot; imageindex=&quot;4&quot; tag=&quot;Integer&quot;&gt;&lt;/fixlets&gt;
        ///      &lt;fixlets text=&quot;Category&quot; imageindex=&quot;6&quot; tag=&quot;String&quot;&gt;&lt;/fixlets&gt;
        ///      &lt;fixlets text=&quot;Download Size&quot; imageindex=&quot;4&quot; tag=&quot;Integer&quot;&gt;&lt;/fixlets&gt;
        ///      &lt;fixlets text=&quot;ID&quot; imageindex=&quot;4&quot; tag=&quot;Integer&quot;&gt;&lt;/fixlets&gt;
        ///      &lt;fixlets text=&quot;Name&quot; imageindex=&quot;6&quot; tag=&quot;String&quot;&gt;&lt;/fixlets&gt;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bes {
            get {
                return ResourceManager.GetString("bes", resourceCulture);
            }
        }
    }
}
